version: "3"
services:
  user-database:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    container_name: user-database
    environment:
      TZ: "Europe/Helsinki"
    env_file:
      - ./.env
    networks:
      - api

networks:
  api:
